"""Exact CVXPY encoding of canonical NCET graphs."""

from dataclasses import dataclass
from typing import Literal

import cvxpy as cp
import numpy as np
from scipy import sparse

from ..errors import UnsupportedOperatorError
from ..ir import GraphIR, IRNode, analyze_capabilities, static_index, validate_ir
from ..passes import Bounds


_SUPPORTED_OPS = frozenset(
    {
        "Input",
        "Linear",
        "Conv2d",
        "BatchNorm",
        "AdaptiveAvgPool2d",
        "AvgPool2d",
        "MaxPool2d",
        "Identity",  # also represents evaluation-mode Dropout
        "ReLU",
        "Add",
        "Sub",
        "Concat",
        "ReduceMean",
        "Flatten",
        "Reshape",
        "Permute",
        "Transpose",
        "GetItem",
        "Slice",
        "Output",
    }
)


@dataclass(frozen=True)
class EncodingOptions:
    """Options that change formulation size without changing exactness.
    Default is "reduced" mode which is more efficient and smaller formulation."""

    relu_binary_mode: Literal["full", "reduced"] = "reduced"


@dataclass(frozen=True)
class EncodedTensor:
    """One per-sample IR tensor represented by a bounded CVXPY variable."""

    expression: cp.Expression
    bounds: Bounds
    shape: tuple[int, ...]


@dataclass(frozen=True)
class ReLUBinaries:
    """Binary vector and the flattened per-sample ReLU positions it represents."""

    variable: cp.Variable        # vectorized ReLU activation variables
    # when reduced mode, only the unstable elements are represented by the binary vector
    # the flat_indices is therefore represents the actual indices of the flattened vector
    flat_indices: np.ndarray 
    # given the flat_indices and original_tensor_shape, 
    # we can convert back to the original tensor coordinates
    original_tensor_shape: tuple[int, ...]


@dataclass(frozen=True)
class MaxPoolBinaries:
    """Full one-hot selectors and their output/input tensor coordinates."""

    # One binary variable represents one valid input-output candidate connection.
    variable: cp.Variable        # vectorized MaxPool activation variables
    # Each kernel window defines a set of input positions that contribute to one output position.
    # Therefore, position k of the output_indices is the output position that is 
    # controlled by the k-th input position.
    # So both output_indices and input_indices are the same size, and they can contain repeated indices.
    # each input position becomes the output position after the MaxPool2d operation.
    output_indices: np.ndarray
    input_indices: np.ndarray


@dataclass(frozen=True)
class EncodingStats:
    """Small formulation summary numbers for the current backend slice."""

    continuous_variables: int
    binary_variables: int
    constraints: int
    always_active_relu: int
    always_inactive_relu: int
    unstable_relu: int   # represented by the binary variables


@dataclass
class MILPEncoding:
    """Graph-aware per-sample variables and constraints generated by NCET."""

    constraints: list[cp.Constraint]
    inputs: dict[str, cp.Expression]  # Named per-sample NN input variables.
    outputs: list[cp.Expression]      # Ordered per-sample NN output variables.
    values: dict[str, EncodedTensor]  # Every per-sample NN tensor and its bounds.
    binaries: dict[str, ReLUBinaries | MaxPoolBinaries]
    graph: GraphIR
    stats: EncodingStats


def encode_cvxpy(
    graph: GraphIR,
    bounds: dict[str, Bounds],
    options: EncodingOptions | None = None,
) -> MILPEncoding:
    """Encode a bounded, per-sample GraphIR as exact CVXPY constraints."""
    validate_ir(graph)
    _require_supported_graph(graph)
    options = options or EncodingOptions()
    if options.relu_binary_mode not in {"full", "reduced"}:
        raise ValueError(
            "relu_binary_mode must be either 'full' or 'reduced'"
        )

    variables = {
        name: cp.Variable(spec.shape, name=f"ncet_{name}")
        for name, spec in graph.tensors.items()
        # each tensor will be represented by a CVXPY variable (including input but without output)
        # spec includes: name, per-sample shape, dtype, producer
    }
    values = {
        name: EncodedTensor(variables[name], bounds[name], spec.shape)
        for name, spec in graph.tensors.items()
    }
    constraints: list[cp.Constraint] = []
    binaries: dict[str, ReLUBinaries | MaxPoolBinaries] = {}
    active_count = inactive_count = unstable_count = 0

    for node in graph.nodes:
        if node.op_type == "Input":
            # Note that multiple inputs will be modelled by multiple Input nodes
            value = variables[node.outputs[0]]
            tensor_bounds = bounds[node.outputs[0]]
            constraints.extend(
                [value >= tensor_bounds.lower, value <= tensor_bounds.upper]
            )
        elif node.op_type == "Linear":
            constraints.append(_linear_constraint(graph, node, variables))
        elif node.op_type == "Conv2d":
            constraints.append(_conv2d_constraint(graph, node, variables))
        elif node.op_type == "BatchNorm":
            constraints.append(_batchnorm_constraint(graph, node, variables))
        elif node.op_type == "AdaptiveAvgPool2d":
            constraints.append(
                _adaptive_avgpool2d_constraint(node, variables)
            )
        elif node.op_type == "AvgPool2d":
            constraints.append(_avgpool2d_constraint(node, variables))
        elif node.op_type == "MaxPool2d":
            pool_constraints, binary = _maxpool2d_constraints(
                node,
                variables,
                bounds[node.inputs[0]],
                bounds[node.outputs[0]],
            )
            constraints.extend(pool_constraints)
            binaries[node.name] = binary
        elif node.op_type == "Identity":
            constraints.append(_identity_constraint(node, variables))
        elif node.op_type in {"Add", "Sub"}:
            constraints.append(_branch_constraint(node, variables))
        elif node.op_type == "Concat":
            constraints.extend(_concat_constraints(node, variables))
        elif node.op_type == "ReduceMean":
            constraints.append(_reduce_mean_constraint(node, variables))
        elif node.op_type in {"Flatten", "Reshape"}:
            constraints.append(_reshape_constraint(node, variables))
        elif node.op_type in {"Permute", "Transpose"}:
            constraints.append(_axis_reorder_constraint(node, variables))
        elif node.op_type in {"GetItem", "Slice"}:
            constraints.append(_index_constraint(node, variables))
        elif node.op_type == "ReLU":
            relu_constraints, binary, counts = _relu_constraints(
                node,
                variables,
                bounds[node.inputs[0]],
                options.relu_binary_mode,
            )
            constraints.extend(relu_constraints)
            if binary is not None:
                binaries[node.name] = binary
            active_count += counts[0]
            inactive_count += counts[1]
            unstable_count += counts[2]

    binary_count = sum(binary.variable.size for binary in binaries.values())
    stats = EncodingStats(
        continuous_variables=sum(variable.size for variable in variables.values()),
        binary_variables=binary_count,
        constraints=len(constraints),
        always_active_relu=active_count,
        always_inactive_relu=inactive_count,
        unstable_relu=unstable_count,
    )
    return MILPEncoding(
        constraints=constraints,
        inputs={name: variables[name] for name in graph.inputs},
        outputs=[variables[name] for name in graph.outputs],
        values=values,
        binaries=binaries,
        graph=graph,
        stats=stats,
    )


def _linear_constraint(
    graph: GraphIR,
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    weight = graph.constants[node.attrs["weight"]]
    bias = graph.constants[node.attrs["bias"]]
    input_value = variables[node.inputs[0]] # the key is the tensor name
    output_value = variables[node.outputs[0]]

    # Because the Torch Linear only operates on the last dimension
    # we flatten the all dimensions except the last one into a 2D matrix
    # for both input and matrix
    rows = int(np.prod(input_value.shape[:-1]))
    input_matrix = cp.reshape(
        input_value,
        (rows, input_value.shape[-1]),
        order="C",
    )
    output_matrix = cp.reshape(
        output_value,
        (rows, output_value.shape[-1]),
        order="C",
    )
    return output_matrix == input_matrix @ weight.T + bias


def _identity_constraint(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Preserve one tensor exactly."""
    # TODO: we can eliminate this constraint by changing the graph structure later
    return variables[node.outputs[0]] == variables[node.inputs[0]]


def _conv2d_constraint(
    graph: GraphIR,
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Encode one per-sample Conv2d as a sparse affine equality."""
    weight = graph.constants[node.attrs["weight"]]
    bias = graph.constants[node.attrs["bias"]]
    input_value = variables[node.inputs[0]]     # In 3D tensor shape: (channels, height, width)
    output_value = variables[node.outputs[0]]

    matrix = _conv2d_affine_matrix(
        weight,
        input_value.shape,
        output_value.shape,
        node.attrs["stride"],
        node.attrs["padding"],
    )
    input_vector = cp.reshape(input_value, (input_value.size,), order="C") # Flatten
    output_vector = cp.reshape(output_value, (output_value.size,), order="C")
    bias_vector = np.repeat(bias, output_value.shape[1] * output_value.shape[2]) # Same bias are shared by one output channel
    return output_vector == matrix @ input_vector + bias_vector


def _batchnorm_constraint(
    graph: GraphIR,
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Encode evaluation-mode BatchNorm as a per-channel affine equality."""
    input_value = variables[node.inputs[0]]
    output_value = variables[node.outputs[0]]
    scale = graph.constants[node.attrs["scale"]]
    shift = graph.constants[node.attrs["shift"]]
    broadcast_shape = (scale.size,) + (1,) * (len(input_value.shape) - 1)
    scale = np.broadcast_to(scale.reshape(broadcast_shape), input_value.shape) # e.g., from (C,) to (C, 1, 1) to (C, H, W)
    shift = np.broadcast_to(shift.reshape(broadcast_shape), input_value.shape)
    return output_value == cp.multiply(scale, input_value) + shift


def _conv2d_affine_matrix(
    weight: np.ndarray,
    input_shape: tuple[int, ...],
    output_shape: tuple[int, ...],
    stride: tuple[int, int],
    padding: tuple[int, int],
) -> sparse.csc_matrix:
    """Return sparse ``A`` such that ``vec_C(Y) = A @ vec_C(X) + b``.
    
    Logic:
    1. In 3D tensor domain, obtain an output position (output_channel, output_row, output_col)
    2. Convert the output position into the position of vectorized output tensor, which is 
        also the row index of the sparse matrix A.
    3. In 3D tensor domain, obtain a position of kernel window (input_channel, kernel_row, kernel_col)
    4. In 3D tensor domain, obtain the corresponding input position (input_channel, input_row, input_col)
    5. Determine if the current input position is padded zero
    5. If not, get the indexed weight which becomes a non-zero coefficient in the sparse matrix A.
    6. Convert the input position into the position of vectorized input tensor, which is 
        also the column index of the sparse matrix A.
    7. Record the row index, column index, and coefficient in the sparse matrix A.
    """
    input_channels, input_height, input_width = input_shape
    output_channels, output_height, output_width = output_shape
    _, _, kernel_height, kernel_width = weight.shape
    stride_height, stride_width = stride
    padding_height, padding_width = padding
    
    # Record the coordinates and coefficients of the non-zero elements in the sparse matrix
    rows: list[int] = []
    columns: list[int] = []
    coefficients: list[float] = []

    # A: (output_channels * output_height * output_width) x (input_channels * input_height * input_width)
    # W: (output_channels, input_channels, kernel_height, kernel_width)
    for output_channel in range(output_channels):
        for output_row in range(output_height):
            for output_col in range(output_width):
                # C-order: channel * height * width + row * width + column
                # Row index of A matrix
                matrix_row = (
                    (output_channel * output_height + output_row)
                    * output_width
                    + output_col
                )

                for input_channel in range(input_channels):
                    for kernel_row in range(kernel_height):
                        # Determine if the current input position is padded zero
                        input_row = (
                            output_row * stride_height
                            + kernel_row
                            - padding_height
                        )
                        if not 0 <= input_row < input_height:
                            continue  # This kernel position lies in zero padding.

                        for kernel_col in range(kernel_width):
                            input_col = (
                                output_col * stride_width
                                + kernel_col
                                - padding_width
                            )
                            if not 0 <= input_col < input_width:
                                continue

                            # Obtain the weight coefficient
                            coefficient = weight[
                                output_channel,
                                input_channel,
                                kernel_row,
                                kernel_col,
                            ]
                            if coefficient == 0:
                                continue

                            # Obtain the input index of vec(X)
                            matrix_col = (
                                (input_channel * input_height + input_row)
                                * input_width
                                + input_col
                            )
                            rows.append(matrix_row)
                            columns.append(matrix_col)
                            coefficients.append(float(coefficient))

    return sparse.coo_matrix(
        (coefficients, (rows, columns)),
        shape=(int(np.prod(output_shape)), int(np.prod(input_shape))),
    ).tocsc()


def _avgpool2d_constraint(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Encode one per-sample AvgPool2d as an exact sparse linear equality."""
    input_value = variables[node.inputs[0]]     # 3D
    output_value = variables[node.outputs[0]]   # 3D
    matrix = _avgpool2d_matrix(
        input_value.shape,
        output_value.shape,
        node.attrs["kernel_size"],
        node.attrs["stride"],
        node.attrs["padding"],
        node.attrs["count_include_pad"],
    )
    input_vector = cp.reshape(input_value, (input_value.size,), order="C")
    output_vector = cp.reshape(output_value, (output_value.size,), order="C")
    return output_vector == matrix @ input_vector


def _adaptive_avgpool2d_constraint(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Encode AdaptiveAvgPool2d as an exact sparse linear equality."""
    input_value = variables[node.inputs[0]]
    output_value = variables[node.outputs[0]]
    matrix = _adaptive_avgpool2d_matrix(
        input_value.shape,
        output_value.shape,
    )
    input_vector = cp.reshape(input_value, (input_value.size,), order="C")
    output_vector = cp.reshape(output_value, (output_value.size,), order="C")
    return output_vector == matrix @ input_vector


def _adaptive_avgpool2d_matrix(
    input_shape: tuple[int, ...],
    output_shape: tuple[int, ...],
) -> sparse.csc_matrix:
    """Build the exact averaging matrix for adaptive pooling windows."""
    channels, input_height, input_width = input_shape
    _, output_height, output_width = output_shape
    rows: list[int] = []
    columns: list[int] = []
    coefficients: list[float] = []

    for channel in range(channels):
        for output_row in range(output_height):
            row_start = output_row * input_height // output_height
            row_end = (
                (output_row + 1) * input_height + output_height - 1
            ) // output_height
            for output_col in range(output_width):
                col_start = output_col * input_width // output_width
                col_end = (
                    (output_col + 1) * input_width + output_width - 1
                ) // output_width
                divisor = (row_end - row_start) * (col_end - col_start)
                # The position of the output vector given by the position of
                # the original position (channel, output_row, output_col)
                matrix_row = (
                    (channel * output_height + output_row) * output_width
                    + output_col
                )

                for input_row in range(row_start, row_end):
                    for input_col in range(col_start, col_end):
                        matrix_col = (
                            (channel * input_height + input_row) * input_width
                            + input_col
                        )
                        rows.append(matrix_row)
                        columns.append(matrix_col)
                        coefficients.append(1.0 / divisor)

    return sparse.coo_matrix(
        (coefficients, (rows, columns)),
        shape=(int(np.prod(output_shape)), int(np.prod(input_shape))),
    ).tocsc()


def _avgpool2d_matrix(
    input_shape: tuple[int, ...],
    output_shape: tuple[int, ...],
    kernel_size: tuple[int, int],
    stride: tuple[int, int],
    padding: tuple[int, int],
    count_include_pad: bool,
) -> sparse.csc_matrix:
    """Return sparse ``A`` such that ``vec_C(Y) = A @ vec_C(X)``."""
    
    # Logic:
    # 1. For a given output position (output_row, output_col),
    #    find all the valid input positions (input_row, input_col) that contribute to the output position.
    # 2. Obtain the divisor for the output position based on the count_include_pad flag.
    # 3. Transform the output position to the corresponding row index of the A matrix.
    # 4. Transform the valid input positions corresponding to the same output position
    #    to the corresponding column indices of the A matrix.
    # 5. Fill the A matrix with the coefficients (1.0 / divisor).
    
    channels, input_height, input_width = input_shape
    _, output_height, output_width = output_shape
    kernel_height, kernel_width = kernel_size
    stride_height, stride_width = stride
    padding_height, padding_width = padding
    
    # To prepare a sparse A matrix
    rows: list[int] = []
    columns: list[int] = []
    coefficients: list[float] = []

    for channel in range(channels):
        # Output and input channels are the same in AvgPool2d
        for output_row in range(output_height):
            for output_col in range(output_width):
                valid_positions: list[tuple[int, int]] = []
                
                # For a given output position (output_row, output_col).
                # find all the valid input positions (input_row, input_col) that contribute to the output position.
                # shared by the same divisor
                for kernel_row in range(kernel_height):
                    # The input coordinate (input_row, input_col) 
                    input_row = (
                        output_row * stride_height
                        + kernel_row
                        - padding_height
                    )
                    if not 0 <= input_row < input_height:
                        continue

                    for kernel_col in range(kernel_width):
                        input_col = (
                            output_col * stride_width
                            + kernel_col
                            - padding_width
                        )
                        if 0 <= input_col < input_width:
                            valid_positions.append((input_row, input_col))

                # Padding zeros are omitted from A. They still count in the
                # divisor only when count_include_pad is true.
                divisor = (
                    kernel_height * kernel_width
                    if count_include_pad
                    else len(valid_positions)
                )
                coefficient = 1.0 / divisor
                # Obtain the row index of the A matrix for the given output position.
                matrix_row = (
                    (channel * output_height + output_row) * output_width
                    + output_col
                )
                
                # Obtain the column indices of the A matrix for the given output position.
                # Lots of positions contribute to one output position.
                for input_row, input_col in valid_positions:
                    matrix_col = (
                        (channel * input_height + input_row) * input_width
                        + input_col
                    )
                    rows.append(matrix_row)
                    columns.append(matrix_col)
                    coefficients.append(coefficient)

    return sparse.coo_matrix(
        (coefficients, (rows, columns)),
        shape=(int(np.prod(output_shape)), int(np.prod(input_shape))),
    ).tocsc()


def _maxpool2d_constraints(
    node: IRNode,
    variables: dict[str, cp.Variable],
    input_bounds: Bounds,
    output_bounds: Bounds,
) -> tuple[list[cp.Constraint], MaxPoolBinaries]:
    """Encode every valid MaxPool2d candidate with a full one-hot selector.

    Logic:
    1. Read the input and output tensors of the canonical MaxPool2d node.
    2. Enumerate the valid input candidates in every output pooling window.
    3. Create one binary selector for every candidate.
    4. Add exact constraints enforcing each output to equal its selected maximum.
    """
    input_value = variables[node.inputs[0]]     # 3D
    output_value = variables[node.outputs[0]]   # 3D

    # At the same position of the list, the map from input indices to output indices are built.
    # output_indices: tuple[int, int, int]
    # input_indices: tuple[int, int, int]
    output_indices, input_indices = _maxpool2d_candidate_indices(
        input_value.shape,
        output_value.shape,
        node.attrs["kernel_size"],
        node.attrs["stride"],
        node.attrs["padding"],
    )
    # Obtain the flat indices of the output and input tensors.
    # After flattening, input_flat[k] -> output_flat[k] still identifies
    # the same candidate connection as input_indices[k] -> output_indices[k].
    output_flat = np.ravel_multi_index(output_indices.T, output_value.shape)
    input_flat = np.ravel_multi_index(input_indices.T, input_value.shape)

    x = cp.reshape(input_value, (input_value.size,), order="C")
    y = cp.reshape(output_value, (output_value.size,), order="C")
    lower_x = input_bounds.lower.reshape(-1)
    lower_y = output_bounds.lower.reshape(-1)
    upper_y = output_bounds.upper.reshape(-1)
    big_m = upper_y[output_flat] - lower_x[input_flat]

    z = cp.Variable(
        len(input_flat),
        boolean=True,
        name=f"ncet_{node.name}_z",
    )
    # One row per output and one column per candidate. Multiplication by z
    # sums exactly the selectors belonging to each pooling window.
    one_hot = sparse.coo_matrix(
        (
            np.ones(len(output_flat)),
            (output_flat, np.arange(len(output_flat))),
        ),
        shape=(output_value.size, len(output_flat)),
    ).tocsc()
    constraints = [
        y >= lower_y,
        y <= upper_y,
        y[output_flat] >= x[input_flat],
        y[output_flat]
        <= x[input_flat] + cp.multiply(big_m, 1 - z),
        one_hot @ z == np.ones(output_value.size),
    ]
    # This metadata creates no new variables; it only maps each z[k] back to
    # its candidate connection: input_indices[k] -> output_indices[k].
    binary = MaxPoolBinaries(
        variable=z,
        output_indices=output_indices,
        input_indices=input_indices,
    )
    return constraints, binary


def _maxpool2d_candidate_indices(
    input_shape: tuple[int, ...],
    output_shape: tuple[int, ...],
    kernel_size: tuple[int, int],
    stride: tuple[int, int],
    padding: tuple[int, int],
) -> tuple[np.ndarray, np.ndarray]:
    """Map every full MaxPool selector to one output and valid input position."""
    channels, input_height, input_width = input_shape
    _, output_height, output_width = output_shape
    kernel_height, kernel_width = kernel_size
    stride_height, stride_width = stride
    padding_height, padding_width = padding
    output_indices: list[tuple[int, int, int]] = []
    input_indices: list[tuple[int, int, int]] = []

    for channel in range(channels):
        for output_row in range(output_height):
            for output_col in range(output_width):
                # Obtain all the valid input positions that contribute to the output position.
                # Because more input positions contribute to the same output position,
                # the output indices are repeated.
                # The input indices are also repeated as the kernel window overlaps
                for kernel_row in range(kernel_height):
                    input_row = (
                        output_row * stride_height
                        + kernel_row
                        - padding_height
                    )
                    if not 0 <= input_row < input_height:
                        continue

                    for kernel_col in range(kernel_width):
                        input_col = (
                            output_col * stride_width
                            + kernel_col
                            - padding_width
                        )
                        if not 0 <= input_col < input_width:
                            continue

                        # For each valid input coordinate, record one aligned
                        # input-coordinate -> output-coordinate pair.
                        output_indices.append(
                            (channel, output_row, output_col)
                        )
                        input_indices.append(
                            (channel, input_row, input_col)
                        )

    return np.asarray(output_indices), np.asarray(input_indices)


def _branch_constraint(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    # Must have two inputs and one output
    left = variables[node.inputs[0]]
    right = variables[node.inputs[1]]
    output = variables[node.outputs[0]]
    operation = left + right if node.op_type == "Add" else left - right
    return output == operation


def _concat_constraints(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> list[cp.Constraint]:
    """Map each input to its contiguous slice of the Concat output."""
    output = variables[node.outputs[0]] # Must only have one output
    dim = node.attrs["dim"]
    constraints: list[cp.Constraint] = []
    start = 0

    # left.shape = (1,4,4); right.shape = (2,4,4); dim = 0
    # Then the index of the output tensor for left is [0:1, :, :] and for right is [1:3, :, :]
    # left: start = 0, stop = 1; right: start = 1, stop = 3

    for input_name in node.inputs:
        input_value = variables[input_name]
        stop = start + input_value.shape[dim]
        # index: [:, :, :]
        index = [slice(None)] * len(output.shape)
        # Replace the dimension with start and stop
        index[dim] = slice(start, stop)
        constraints.append(output[tuple(index)] == input_value)
        start = stop

    return constraints


def _reshape_constraint(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Preserve C-order element positions while changing tensor shape.
    Vectorize the input and output tensors and enforce the equality as constraints
    """
    input_value = variables[node.inputs[0]]
    output_value = variables[node.outputs[0]]
    input_vector = cp.reshape(input_value, (input_value.size,), order="C")
    output_vector = cp.reshape(output_value, (output_value.size,), order="C")
    return output_vector == input_vector


def _reduce_mean_constraint(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Average over fixed sample axes using one exact linear equality."""
    input_value = variables[node.inputs[0]]
    output_value = variables[node.outputs[0]]
    dims = node.attrs["dims"]
    element_count = int(np.prod([input_value.shape[dim] for dim in dims]))
    keepdim = node.attrs["keepdim"]
    total = input_value
    # Descending axes keep lower axis numbers valid when keepdim=False.
    for dim in sorted(dims, reverse=True):
        total = cp.sum(total, axis=dim, keepdims=keepdim)
    mean = total / element_count
    return output_value == mean


def _axis_reorder_constraint(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Reorder sample axes with CVXPY's native N-dimensional permutation."""
    input_value = variables[node.inputs[0]]
    output_value = variables[node.outputs[0]]

    if node.op_type == "Permute":
        dims = node.attrs["dims"]
    else:
        # Transpose
        dims = list(range(len(input_value.shape)))
        dim0, dim1 = node.attrs["dim0"], node.attrs["dim1"]
        dims[dim0], dims[dim1] = dims[dim1], dims[dim0]

    return output_value == cp.permute_dims(input_value, axes=tuple(dims))


def _index_constraint(
    node: IRNode,
    variables: dict[str, cp.Variable],
) -> cp.Constraint:
    """Select a canonical static index without introducing binaries."""
    input_value = variables[node.inputs[0]]
    output_value = variables[node.outputs[0]]
    return output_value == input_value[static_index(node)]


def _relu_constraints(
    node: IRNode,
    variables: dict[str, cp.Variable],
    input_bounds: Bounds,
    mode: Literal["full", "reduced"],
) -> tuple[
    list[cp.Constraint],
    ReLUBinaries | None,
    tuple[int, int, int],
]:

    input_value = variables[node.inputs[0]]
    output_value = variables[node.outputs[0]]
    size = input_value.size
    
    # For element-wise ReLU, flatten does not change the operation
    x = cp.reshape(input_value, (size,), order="C")
    y = cp.reshape(output_value, (size,), order="C")
    lower = input_bounds.lower.reshape(-1)
    upper = input_bounds.upper.reshape(-1)

    active = np.flatnonzero(lower >= 0)  # y_i = x_i, no binary variable needed
    inactive = np.flatnonzero((upper <= 0) & (lower < 0))  # y_i = 0, no binary variable needed
    unstable = np.flatnonzero((lower < 0) & (upper > 0))   # with binary variable needed
    constraints: list[cp.Constraint] = []

    if mode == "reduced":
        if active.size:
            constraints.append(y[active] == x[active])
        if inactive.size:
            constraints.append(y[inactive] == 0)
        binary_indices = unstable
    else:
        binary_indices = np.arange(size)

    binary = None
    # binary_indices is the indices in vector form.
    if binary_indices.size:
        # Only create binary variables for unstable ReLU elements
        z = cp.Variable(
            binary_indices.size,
            boolean=True,
            name=f"ncet_{node.name}_z",
        )
        x_binary = x[binary_indices]
        y_binary = y[binary_indices]
        lower_binary = lower[binary_indices]
        upper_binary = upper[binary_indices]
        constraints.extend(
            [
                y_binary >= x_binary,
                y_binary >= 0,
                y_binary <= x_binary - cp.multiply(lower_binary, 1 - z),
                y_binary <= cp.multiply(upper_binary, z),
            ]
        )
        # For reduced mode, we have z.size == len(binary_indices) <= np.prod(original_tensor_shape)
        # For full mode, we have z.size == len(binary_indices) == np.prod(original_tensor_shape)
        binary = ReLUBinaries(
            variable=z,
            flat_indices=binary_indices,
            original_tensor_shape=input_value.shape,
        )

    counts = (active.size, inactive.size, unstable.size)
    return constraints, binary, counts


def _require_supported_graph(graph: GraphIR) -> None:
    report = analyze_capabilities(graph, _SUPPORTED_OPS)
    if report.supported:
        return

    unsupported = ", ".join(
        f"{node.name} ({node.op_type})" for node in report.unsupported_nodes
    )
    raise UnsupportedOperatorError(
        f"CVXPY encoding does not support graph nodes: {unsupported}"
    )
